# Generated by Django 3.2 on 2022-11-30 19:24

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_schema',
            fields=[
                ('key_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('address', jsonfield.fields.JSONField(default=dict)),
                ('schema', jsonfield.fields.JSONField(default=dict)),
                ('category_rank', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('hash_password', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField()),
                ('unique_hash', models.CharField(max_length=100)),
                ('engine_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('address', jsonfield.fields.JSONField(default=dict)),
                ('schema_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.category_schema', verbose_name='Category')),
            ],
        ),
    ]
